2023/10/12 更新

diff --git a/resource/script/generate_root b/resource/script/generate_root
--- a/resource/script/generate_root
+++ b/resource/script/generate_root
@@ -3,38 +3,40 @@
 # ライブラリ読み出し
 source "$(dirname $0)/library.sh"
 
-# 環境の読み出し
-if [ -f "$(dirname $0)/.env" ]; then
-  source "$(dirname $0)/.env"
+
+# 機密情報の読み出し
+if [ "$SECRET_FILE" != '' -a -f "$SECRET_FILE" ]; then
+  source "$SECRET_FILE"
 fi
 
-# 設定ファイルのディレクトリ
-CONFIG_DIR="${CONFIG_DIR:=.}"
+
+# パスフレーズ読み取り
+ROOT_CA_PASSWORD="${ROOT_CA_PASSWORD:=""}"
+if [ "$ROOT_CA_PASSWORD" == '' ]; then
+  verifyPassword \
+    'Input root CA passphrase:' \
+    'Verify root CA passphrase:' \
+    ROOT_CA_PASSWORD
+
+  if [ $? -ne 0 ]; then
+    echo 'Password mismatch' > /dev/stderr
+    exit 1
+  fi
+fi
+
 
 # 初期化
-ROOT_CA_DIR="${ROOT_CA_DIR:='/etc/ssl/root_ca'}"
+ROOT_CA_DIR="${ROOT_CA_DIR:="/etc/ssl/root_ca"}"
 if [ ! -d "$ROOT_CA_DIR" ]; then
   mkdir "$ROOT_CA_DIR"
 fi
 initializeCADir "$ROOT_CA_DIR"
 
-# パスフレーズ読み取り
-PASSWORD=''
-verifyPassword \
-  'Input root CA passphrase:' \
-  'Verify root CA passphrase:' \
-  PASSWORD
-
-if [ $? -ne 0 ]; then
-  echo 'Password mismatch' > /dev/stderr
-  exit 1
-fi
-
 
 # 鍵生成
 openssl genrsa \
   -batch \
-  -passout "pass:$PASSWORD" \
+  -passout "pass:$ROOT_CA_PASSWORD" \
   -out "$ROOT_CA_DIR/private/private_key.pem" \
   -aes-256-cbc \
   4096
@@ -48,17 +50,17 @@ fi
 # リクエスト
 openssl req \
   -batch -new -utf8  \
-  -config "$CONFIG_DIR/openssl.cfg" \
+  -config "$CONFIG_FILE" \
   -section req_RootCA \
   -extensions root_ca \
-  -passin "pass:$PASSWORD" \
+  -passin "pass:$ROOT_CA_PASSWORD" \
   -keyform PEM \
   -key "$ROOT_CA_DIR/private/private_key.pem" \
   -outform PEM \
   -out "$ROOT_CA_DIR/root_ca.csr"
 
 if [ $? -ne 0 ]; then
-  echo 'Failed to generate requeset.' > /dev/stderr
+  echo "Failed to generate requeset. ($CONFIG_FILE)" > /dev/stderr
   exit 1
 fi
 
@@ -66,12 +68,12 @@ fi
 # 署名
 openssl ca \
   -batch \
-  -config "$CONFIG_DIR/openssl.cfg" \
+  -config "$CONFIG_FILE" \
   -section CA_root \
   -extensions root_ca \
   -md sha256 \
   -in "$ROOT_CA_DIR/root_ca.csr" \
-  -passin "pass:$PASSWORD" \
+  -passin "pass:$ROOT_CA_PASSWORD" \
   -selfsign \
   -cert "$ROOT_CA_DIR/certs/root_ca.crt" \
   -keyform PEM \
@@ -85,5 +87,5 @@ if [ $? -ne 0 ]; then
 fi
 
 # 確認
-# openssl rsa -noout -text -passin "pass:${PASSWORD}" -in "$ROOT_CA_DIR/private/private_key.pem" 
+# openssl rsa -noout -text -passin "pass:${ROOT_CA_PASSWORD}" -in "$ROOT_CA_DIR/private/private_key.pem" 
 # openssl x509 -batch -noout -text -in ./root_ca.crt
diff --git a/resource/script/generate_server b/resource/script/generate_server
--- a/resource/script/generate_server
+++ b/resource/script/generate_server
@@ -3,48 +3,52 @@
 # ライブラリ読み出し
 source "$(dirname $0)/library.sh"
 
-# 環境の読み出し
-if [ -f "$(dirname $0)/.env" ]; then
-  source "$(dirname $0)/.env"
+
+# 機密情報の読み出し
+if [ "$SECRET_FILE" != '' -a -f "$SECRET_FILE" ]; then
+  source "$SECRET_FILE"
 fi
 
-# 設定ファイルのディレクトリ
-CONFIG_DIR="${CONFIG_DIR:=.}"
-
-# 初期化
-ROOT_CA_DIR="${ROOT_CA_DIR:='/etc/ssl/root_ca'}"
-INTER_CA_DIR="${INTER_CA_DIR:='/etc/ssl/inter_ca'}"
-
-# ドメイン名(DN; Distinguished Name)
-DN=${DN:='apps.localdomain'}
-SUBJECT=${SUBJECT:="/C=JP/CN=$DN"}
-SAN=${SAN:="DNS:$DN,DNS:app1.apps.localdomain"}
 
 # パスフレーズ読み取り
-INTER_CA_PASSWORD=${INTER_CA_PASSWORD:=''}
+INTER_CA_PASSWORD="${INTER_CA_PASSWORD:=""}"
 if [ "$INTER_CA_PASSWORD" == '' ]; then
   readPassword \
     "Input intermediate CA passphrase: " \
     INTER_CA_PASSWORD
 fi
 
-PASSWORD=''
-verifyPassword \
-  'Input private key passphrase:' \
-  'Verify private key passphrase:' \
-  PASSWORD
+SERVER_PASSWORD="${SERVER_PASSWORD:=""}"
+if [ "$SERVER_PASSWORD" == '' ]; then
+  verifyPassword \
+    'Input private key passphrase:' \
+    'Verify private key passphrase:' \
+    SERVER_PASSWORD
 
-if [ $? -ne 0 ]; then
-  echo 'Password mismatch' > /dev/stderr
-  exit 1
+  if [ $? -ne 0 ]; then
+    echo 'Password mismatch' > /dev/stderr
+    exit 1
+  fi
 fi
+
+
+# 初期化
+ROOT_CA_DIR="${ROOT_CA_DIR:="/etc/ssl/root_ca"}"
+INTER_CA_DIR="${INTER_CA_DIR:="/etc/ssl/inter_ca"}"
+
+echo "DN = $DN, SUBJECT = $SUBJECT, SAN = $SAN"
+
+# ドメイン名(DN; Distinguished Name)
+DN="${DN:="apps.localdomain"}"
+SUBJECT="${SUBJECT:="/C=JP/CN=$DN"}"
+SAN="${SAN:="DNS:$DN,DNS:app1.apps.localdomain"}"
 
 
 # 鍵生成
 openssl genrsa \
   -batch \
-  -passout "pass:$PASSWORD" \
-  -out "$DN.private_key.pem" \
+  -passout "pass:$SERVER_PASSWORD" \
+  -out "$INTER_CA_DIR/private/$DN.pem" \
   -aes-256-cbc \
   4096
 
@@ -54,15 +58,26 @@ if [ $? -ne 0 ]; then
 fi
 
 
+# パスフレーズレス秘密鍵生成
+openssl rsa \
+  -passin "pass:$SERVER_PASSWORD" \
+  -in "$INTER_CA_DIR/private/$DN.pem" \
+  -out "$INTER_CA_DIR/private/$DN.nopass.pem"
+
+if [ $? -ne 0 ]; then
+  echo 'Failed to generate ras key without passphrase.' > /dev/stderr
+  exit 1
+fi
+
 # リクエスト
 openssl req -new -utf8 \
   -batch \
   -subj "$SUBJECT" \
   -addext "subjectAltName = $SAN" \
-  -passin "pass:$PASSWORD" \
+  -passin "pass:$SERVER_PASSWORD" \
   -keyform PEM \
-  -key "$DN.private_key.pem" \
-  -out "$DN.csr"
+  -key "$INTER_CA_DIR/private/$DN.pem" \
+  -out "$INTER_CA_DIR/requests/$DN.csr"
 
 if [ $? -ne 0 ]; then
   echo 'Failed to generate requeset.' > /dev/stderr
@@ -73,7 +88,7 @@ fi
 # 署名
 openssl ca \
   -batch \
-  -config "$CONFIG_DIR/openssl.cfg" \
+  -config "$CONFIG_FILE" \
   -section CA_inter \
   -extensions web_server_ca \
   -md sha256 \
@@ -82,8 +97,8 @@ openssl ca \
   -keyform PEM \
   -keyfile "$INTER_CA_DIR/private/private_key.pem" \
   -cert "$INTER_CA_DIR/certs/inter_ca.crt" \
-  -in "$DN.csr" \
-  -out "$DN.crt"
+  -in "$INTER_CA_DIR/requests/$DN.csr" \
+  -out "$INTER_CA_DIR/certs/$DN.crt"
 
 if [ $? -ne 0 ]; then
   echo 'Failed to generate certificate.' > /dev/stderr
@@ -94,10 +109,10 @@ fi
 # チェーン生成
 openssl crl2pkcs7 \
   -nocrl \
-  -certfile "$DN.crt" \
+  -certfile "$INTER_CA_DIR/certs/$DN.crt" \
   -certfile "$INTER_CA_DIR/certs/inter_ca.crt" \
   -certfile "$ROOT_CA_DIR/certs/root_ca.crt" \
-  -out "$DN.chain.p7b"
+  -out "$INTER_CA_DIR/certs/$DN.chain.p7b"
 
 if [ $? -ne 0 ]; then
   echo 'Failed to generate certificate chain.' > /dev/stderr
@@ -106,13 +121,6 @@ fi
 
 
 # Nginx向け証明書チェーン
-cat "$DN.crt" > "$DN.chain.crt"
-cat "$INTER_CA_DIR/certs/inter_ca.crt" >> "$DN.chain.crt"
-cat "$ROOT_CA_DIR/certs/root_ca.crt" >> "$DN.chain.crt"
-
-
-# パスフレーズレス秘密鍵生成
-openssl rsa \
-  -passin "pass:$PASSWORD" \
-  -in "$DN.private_key.pem" \
-  -out "$DN.private_key.nopass.pem"
+cat "$INTER_CA_DIR/certs/$DN.crt"      >  "$INTER_CA_DIR/certs/$DN.chain.crt"
+cat "$INTER_CA_DIR/certs/inter_ca.crt" >> "$INTER_CA_DIR/certs/$DN.chain.crt"
+cat "$ROOT_CA_DIR/certs/root_ca.crt"   >> "$INTER_CA_DIR/certs/$DN.chain.crt"
